version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
      - image: mongo
    steps:
      - checkout
      - run: 'make init && python3 sample'
  test:
    docker:
      - image: circleci/python:3.7.2
      - image: mongo
    steps:
      - checkout
      - run: 'make init && make test'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
